import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { LocalizedStringProvider } from 'react-aria-components/i18n';

import './globals.css';

const roboto = Roboto({
  weight: ['400', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body className={roboto.className}>
        <LocalizedStringProvider locale="it" />
        {children}
      </body>
    </html>
  );
}
