import type { Metadata } from 'next';
import { headers } from 'next/headers';

import {
  cachedGetUser,
  getConfig,
  getUserUpdatesCount,
} from '@/services/firebase/server';
import { Header, HeaderModal } from '@/components/header/header';
import styles from './layout.module.css';
import {
  checkCanEditIssues,
  checkCanEditRiscossi,
} from '@/services/firebase/server/permissions';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentHeaders = await headers();
  const { currentUser } = await cachedGetUser(currentHeaders);

  const [issuesUpdatesCount, riscossiUpdatesCount] = currentUser?.id
    ? await Promise.all([
        checkCanEditIssues(currentUser?.permissions)
          ? await getUserUpdatesCount(currentHeaders, currentUser.id, 'issues')
          : 0,
        checkCanEditRiscossi(currentUser?.permissions)
          ? await getUserUpdatesCount(
              currentHeaders,
              currentUser.id,
              'riscossi'
            )
          : 0,
      ])
    : [0, 0];

  const updates = {
    issues: issuesUpdatesCount,
    riscossi: riscossiUpdatesCount,
  };

  const config = await getConfig(currentHeaders);

  return (
    <div className={styles.container}>
      <div className={styles.sidebar}>
        {currentUser && (
          <Header
            mailUrl={config.mailUrl}
            permissions={currentUser.permissions}
            theme={currentUser.theme}
            updates={updates}
          />
        )}
      </div>
      <div className={styles.content}>{children}</div>
      <div className={styles.mobileSidebar}>
        {currentUser && (
          <HeaderModal
            mailUrl={config.mailUrl}
            permissions={currentUser.permissions}
            theme={currentUser.theme}
            updates={updates}
          />
        )}
      </div>
    </div>
  );
}
