import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { headers } from 'next/headers';

import { cachedGetUser } from '@/services/firebase/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentHeaders = await headers();
  const { currentUser } = await cachedGetUser(currentHeaders);

  if (!currentUser) {
    return redirect('/signin');
  }

  return (
    <div className="theme-provider" data-theme={currentUser.theme}>
      {children}
    </div>
  );
}
